### ISSUE TITLE
Suggestion: More Organised README

### ISSUE THREAD

**Issue by yigitozkavci** [yasintoy/Slack-Gitsin#13]
Currently, when user visits the README page, after the `Installation` part, finds himself in `Notifications` and `TODO` part which I think are not relevant & shouldn't be there. I suggest a categorisation like this:
- Problem
- Installation
- Getting Started
- Advanced Usage(we can mention some extras here)
- TODO
- Contributing
- Licence

What do you think?

**Comment by yigitozkavci** [comment]
Actually the thing is, even though I read all the readme, I could not find a way to get started with basic usage. I had to look into code to figure out some commands & usage. 
We can make it more end-user-friendly.

**Comment by yasintoy** [comment]
@yigitozkavci  my priority is adding real time chat features. I'm trying to make this but if you want you can organize README while I'm working on this?

**Comment by yigitozkavci** [comment]
Of course I will work on this, I was just making sure that it would be appropriate :)
