### ISSUE TITLE
What is the right command to run?

### ISSUE THREAD

**Issue by yigitozkavci** [yasintoy/Slack-Gitsin#16]
On Mac OS X, I need to run `python main.py` in order to get in to the buffer.
If this is the case, should we tell people to run this command in order to get started? Because I needed to look into the source code to figure it out.

**Comment by AFAgarap** [comment]
Well, on GNU/Linux as well. @yasintoy I hope you would consider this additional instruction in the <a href="https://github.com/yasintoy/Slack-Gitsin/blob/master/README.md">README.md</a> :) More power!
