### ISSUE TITLE
Making setup.py file

### ISSUE THREAD

**Issue by yasintoy** [yasintoy/Slack-Gitsin#5]
make setup.py

**Comment by den-run-ai** [comment]
+1 - cannot install on windows

**Comment by yasintoy** [comment]
@denfromufa we don't support windows yet:( only mac and linux

**Comment by szabolcsdombi** [comment]
An example for setup.py [here](https://github.com/cprogrammer1994/ExtendingPythonTutorial)
You won't need the Extension part here so cut it out.

This example involves a package, a sub-package and some modules.
