### ISSUE TITLE
Real time messaging

### ISSUE THREAD

**Issue by yasintoy** [yasintoy/Slack-Gitsin#6]
When I first started to this project, I thought that it'll be just for special times(vagrant+spotify+slack+chrome+pycharm) but now, I changed my mind. People loved SlackGitsin so we'll make it better together. Real time chat will be added soon.

**Comment by deadbits** [comment]
Just curious why this Issue was closed? Does it now support real-time chat or is this project no longer maintained? I don't see anything in the README or the source / commit history that indicates it does support it, so just wondering on this projects status (and this ticket specifically) 
:)

**Comment by yasintoy** [comment]
project no longer maintained :( @deadbits

**Comment by yigitozkavci** [comment]
You should probably put a message as announcement on README @yasintoy

**Comment by deadbits** [comment]
Thanks for the update @yasintoy! And I agree with @yigitozkavci  :)
