### ISSUE TITLE
Possibility of adding homebrew formula?

### ISSUE THREAD

**Issue by benadamstyles** [yasintoy/Slack-Gitsin#8]
Would significantly lower the barrier to entry. This looks great btw!

**Comment by yasintoy** [comment]
Thanks for your interest. I'd love to make this.

**Comment by yasintoy** [comment]
@Leeds-eBooks Hey, again. Would you like to help me to create homebrew formula? Nowadays, I'm trying to fix some bugs and add new features so if you can help me, I'll really appreciate it :)

**Comment by benadamstyles** [comment]
I'm sorry man but with my current workload (day job + startup) there is no way I could attend to this within the next month, plus I don't know Ruby at all! 😢
